# This workflow will build a package using Maven and then publish it to GitHub and Sonatype snapshots repository when merged to master
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package Snapshot

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Publish to GitHub Packages Apache Maven
        run: ./mvnw deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/esensar/neovim-http-api-plugin -Dtoken=$GITHUB_TOKEN -P github -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
